### PR TITLE
Adding parallel steps

### PR DESCRIPTION
**Pull request by mons3rrat**

### CODE REVIEW

**Comment by gmlp** [comment]
@mons3rrat, I did a merge to dev including the java example application. could you please integrate those changes?.

**Comment by mons3rrat** [comment]
> @mons3rrat, I did a merge to dev including the java example application. could you please integrate those changes?.

done!

**Comment by gmlp** [comment]
@mons3rrat can you do a git squash to have only one commit, please let me know  If you have any doubt .

**Comment by gmlp** [comment]
@mons3rrat, everything else LGTM.

**Pull request merged**
